### ISSUE TITLE
DatMaker doesn't write apostrophes correctly 

### ISSUE THREAD

**Issue by LnmVolbo** [gjefferyes/RomVault#17]
@gjefferyes,

When making a dir2dat, the "clean" routine overdoes it when translating the apostrophes.  This code is from DatMaker.cs:

        private static string clean(string s)
        {
            s = s.Replace("\"", "&quot;");
            s = s.Replace("'", "&apos;");
            s = s.Replace("<", "&lt;");
            s = s.Replace(">", "&gt;");
            s = s.Replace("&", "&amp;");
            return s;
        }

Since the code does a series of five replacements, the line that changes the apostrophe replaces it with a string starting with ampersand, followed by other chars.  A couple of lines down, the ampersands get replaced by an ampersand, followed by other chars. This means that any apostrophe will end up being replaced by the string "@amp;apos;".  When this is re-read as a new .dat file, it becomes "@apos;", instead of " ' " (a single apostrophe character) when viewing it in the GameGrid, and when rebuilding the file.  Not good.

There are two ways to fix this, one, add this line just before the return statement:

            s = s.Replace("&amp;apos;", "&apos;");

Or better yet, do the replacement of ampersand before the replacement of apostrophe.

This is sort of a zero-liner (not even a one-liner) as the issue can be fixed by switching around the order of the statements.

The other "clean" routine in the code, in Report.cs, already has the proper statement order.  Probably just an oversight to miss this one in DatMaker.cs.  Since the DatMaker isn't used very much.  And most mainline collections have few, if any, apostrophes.

**Comment by gjefferyes** [comment]
Fixed this by changing the order of the replace's
