### ISSUE TITLE
DatMaker: doesn't handle CHDs, doesn't pass descriptions, doesn't indent with tabs.

### ISSUE THREAD

**Issue by LnmVolbo** [gjefferyes/RomVault#38]
The DatMaker works great for ROMs, but has some issues when CHDs are in the mix.  This issue fix combines three issues and fixes them.

Issue 1. Formerly the DatMaker created a bunch of empty "&lt;dir&gt;" tags instead of the expected CHD information.  This issue fix address that, and populates the correct CHD info instead.  The CHD info availible in ROMVault's internal database includes both "disk" type info (internal sha-1 only), as well as "rom" type info (size, crc, md5, and external sha-1).  So the context menu on the DirTree control was augmented to allow the user to choose to make a .dat file either using the "disk" info or "rom" info.

This is important when making a .dat file from an incomplete collection.  If the .dat loaded into ROMVault is of the "disk" type, there won't be any info for the CHD "rom" type info for CHDs that are uncollected, and the resulting .dat will be pretty useless.  And vica-versa, if the underlying .dat is a "rom" type there will not be any internal sha-1 info (on the uncollected CHDs) to regurgitate into the made .dat file.

When making a dat from a complete collection, there is no issue, as both kinds of data will be in ROMVault's internal database. (Except for "nodumps", of course)

Issue 2.  Formerly the DatMaker always used the "name" for the description. This new revision digs the proper description out of ROMVault's internal database and uses it, unless it is missing. (In which case it will fall back on duplicating the "name" field.)

Issue 3.  Formerly the DataMaker used a string of four spaces for the indent in the xml code.  This has been changed to a tab character.  This is not a critical item, more of a personal preference.  When you edit a lot of .dat files manually, it's a little faster to arrow thru the tabs than all those spaces when there is a lot of nesting.  If not accepted into the official version, perhaps the choice, (tabs or spaces) could be added as an option setting.

This has only been tested on a limited number of .dat files and collections.  I am putting this up in this initial form to see if anyone has any issues with whatever .dat files and collections they commonly use.  I am sure there is room for improvement, please post .dat files, and/or .dat folderstructures that are not replicated properly using this new DatMaker routine.

DatMaker.cs has the changes that address the three issues mentioned.
[DatMaker.zip](https://github.com/gjefferyes/RomVault/files/290062/DatMaker.zip) (3 KB)

FrmMain.cs has changes that allow the user to select which type of .dat to be made from the context (right-click) menu of the DirTree. (It also has the code from issue #35)
[FrmMain.zip](https://github.com/gjefferyes/RomVault/files/290060/FrmMain.zip) (10 KB)

Linked below is a windows binary with the changes for testing if you do not wish to compile your own.  This is compiled with VS2015 on win7.  For reasons I do not understand (I just started with VS2015 and my older versions of VS are unavailable), there is an xml-content config file (named "ROMVault226x.exe.config") that seems to be needed in order for the compiled app to function properly.  I have included the .config file along with the .exe in the .zip.  I have named the .exe file "ROMVault226x.exe", with the x suffix for "experimental".

Link: https://www.sendspace.com/file/lo6u3g (460 KB)

I don't expect these code additions to be added "as-is" to the official source.  It's just a starting point to get the ball rolling.

With these changes, it's up to the user to decide which kind of .dat file to produce (disk or rom).  A further enhancement could be for ROMVault to detect which type is inappropriate (due to an incomplete collection) and disable the wrong choice from the DirTree context menu.

**Comment by gjefferyes** [comment]
Added to source
